app:
  frontend: 'http://localhost:19006'

server:
  port: 3000

db:
  type: 'postgres'
  port: '5432'
  database: 'quickstack'

jwt:
  expiresIn: 36000

mail:
  from: 'backend@quickstack.com'
  host: 'smtp.ethereal.email'
  port: 587
  user: config.ethereal.username
  pass: config.ethereal.password
